name: web

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      NEXT_PUBLIC_BACKEND_URL: ${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
      NEXT_PUBLIC_ENVIRONMENT_LABEL: ${{ vars.NEXT_PUBLIC_ENVIRONMENT_LABEL || 'ci' }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      NEXT_PUBLIC_ONBOARDING_PUBLIC_TOKEN: ${{ secrets.NEXT_PUBLIC_ONBOARDING_PUBLIC_TOKEN }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SITE_SUPABASE_URL: ${{ secrets.SITE_SUPABASE_URL }}
      SITE_SUPABASE_SECRET_KEY: ${{ secrets.SITE_SUPABASE_SECRET_KEY }}
      ONBOARDING_API_TOKEN: ${{ secrets.ONBOARDING_API_TOKEN }}
      META_WABA_PHONE_NUMBER_ID: ${{ secrets.META_WABA_PHONE_NUMBER_ID }}
      META_WABA_ACCESS_TOKEN: ${{ secrets.META_WABA_ACCESS_TOKEN }}
      OTP_TEMPLATE_NAME: ${{ secrets.OTP_TEMPLATE_NAME }}
      OTP_TEMPLATE_LANGUAGE: ${{ secrets.OTP_TEMPLATE_LANGUAGE }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Type check
        run: npm run typecheck
      - name: Unit tests
        run: npm run test:unit
      - name: Build web bundle
        run: npm run build
      - name: Upload Next.js artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-standalone
          path: .next
      - name: Lighthouse CI
        if: ${{ github.event_name == 'pull_request' }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: npm run lint:pwa
      - name: SBOM (CycloneDX)
        run: npx @cyclonedx/cyclonedx-npm --output-format json --output-file sbom-web.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: web-sbom
          path: sbom-web.json
