# ---- Build stage ----
FROM node:20-alpine AS builder
WORKDIR /app

# Install dependencies with npm (project uses npm@11)
COPY package.json package-lock.json ./
RUN npm ci

# Copy source and build standalone output
COPY . .
RUN npm run build

# ---- Runtime stage ----
FROM node:20-alpine
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Copy standalone server and assets generated by Next.js
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000
CMD ["node", "server.js"]
