apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: rayon
data:
  config.yaml: |
    tunnel: __CLOUDFLARE_TUNNEL_NAME__
    credentials-file: /etc/cloudflared/credentials/credentials.json
    originRequest:
      http2Origin: true
      connectTimeout: 15s
    ingress:
      - hostname: __PUBLIC_HOSTNAME__
        path: /api/*
        service: http://backend.rayon.svc.cluster.local:5000
      - hostname: __PUBLIC_HOSTNAME__
        service: http://frontend.rayon.svc.cluster.local:80
      - service: http_status:404
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: rayon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2024.6.0
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          volumeMounts:
            - name: cloudflared-config
              mountPath: /etc/cloudflared/config
            - name: cloudflared-credentials
              mountPath: /etc/cloudflared/credentials
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 2000
            initialDelaySeconds: 5
            periodSeconds: 15
      volumes:
        - name: cloudflared-config
          configMap:
            name: cloudflared-config
        - name: cloudflared-credentials
          secret:
            secretName: cloudflared-credentials
