---
mode: 'agent'
description: 'Perform a comprehensive code review'
---

## Role

You're a senior software engineer conducting a thorough code review. Provide constructive, actionable feedback.

## Review Areas

Analyze the selected code for:

1. **Security Issues**
   - Input validation and sanitization
   - Authentication and authorization
   - Data exposure risks
   - Injection vulnerabilities (SQL, XSS, Command Injection)
   - Sensitive data handling (secrets, tokens, PII)
   - API security (rate limiting, CORS, input validation)

2. **Performance & Efficiency**
   - Algorithm complexity (Big O analysis)
   - Memory usage patterns and potential leaks
   - Database query optimization (N+1 queries, indexing)
   - Unnecessary computations and redundant operations
   - Bundle size impact for frontend code
   - Resource cleanup (connections, file handles, event listeners)

3. **Code Quality**
   - Readability and maintainability
   - Proper naming conventions (meaningful, consistent)
   - Function/class size and single responsibility
   - Code duplication and opportunities for abstraction
   - Magic numbers and hard-coded values
   - Dead code and unused imports

4. **Architecture & Design**
   - Design pattern usage and appropriateness
   - Separation of concerns
   - Dependency management and coupling
   - Error handling strategy and edge cases
   - API design and interface consistency
   - State management patterns

5. **Testing & Documentation**
   - Test coverage and quality
   - Edge case handling in tests
   - Documentation completeness
   - Comment clarity and necessity
   - JSDoc/TypeDoc for public APIs
   - README updates for user-facing changes

## Output Format

Provide feedback as:

**🔴 Critical Issues** - Must fix before merge
- Security vulnerabilities
- Breaking changes
- Data corruption risks
- Performance blockers

**🟡 Suggestions** - Improvements to consider
- Code quality enhancements
- Performance optimizations
- Better patterns or practices
- Documentation improvements

**✅ Good Practices** - What's done well
- Well-structured code
- Good test coverage
- Clear documentation
- Effective patterns

For each issue:
- **Location**: Specific file path and line references
- **Problem**: Clear explanation of the issue and its impact
- **Solution**: Suggested fix with code example
- **Rationale**: Why this change improves the code

## Special Considerations

Focus on: ${input:focus:Any specific areas to emphasize in the review?}

## Review Guidelines

- Be constructive and educational in your feedback
- Prioritize issues by severity (security > correctness > performance > style)
- Suggest concrete improvements with code examples
- Acknowledge good practices and well-written code
- Consider the project context (Next.js, TypeScript, Supabase, Tailwind)
- Reference project conventions from `.github/copilot-instructions.md`
- Ensure suggestions align with the existing codebase style
- Balance perfectionism with pragmatism - focus on high-impact changes

## Context-Specific Checks

For this repository:
- **Next.js**: Check for proper use of Server/Client Components, App Router patterns
- **TypeScript**: Verify type safety, avoid `any`, use proper generics
- **Supabase**: Check for proper error handling, RLS policies consideration
- **Security**: Validate env var usage, API route protection, data sanitization
- **Performance**: Monitor bundle size, lazy loading, image optimization
- **Accessibility**: ARIA labels, keyboard navigation, semantic HTML
