insert into public.users (name, phone, momo_number, tier, points)
values ('Guest Fan', '0780000000', '0780000000', 'fan', 1200)
on conflict do nothing;

insert into public.matches (title, comp, date, venue, status, home_team, away_team, vip_price, regular_price, seats_vip, seats_regular)
values
('Rayon vs APR', 'Rwanda Premier League', now() + interval '3 day', 'Amahoro', 'upcoming', 'Rayon', 'APR', 15000, 5000, 420, 3510),
('Rayon vs Police', 'Rwanda Premier League', now() + interval '10 day', 'Kigali', 'upcoming', 'Rayon', 'Police', 15000, 5000, 420, 3510);

insert into public.shop_products (name, category, price, stock, description, image_url, badge)
values
('Home Jersey 24/25', 'jerseys', 25000, 25, 'Official home kit', '/shop/home1.png', 'official'),
('Away Jersey 24/25', 'jerseys', 25000, 18, 'Official away kit', '/shop/away1.png', 'official'),
('Scarf Classic', 'accessories', 10000, 40, 'Warm knit scarf', '/shop/scarf1.png', 'sale');

-- Admin locale seeds
insert into public.translations (lang, key, value) values
  ('en', 'admin.shell.nav.disabled', 'Off'),
  ('en', 'admin.toast.denied.title', 'Access denied'),
  ('en', 'admin.toast.denied.generic', 'You do not have permission to access that section.'),
  ('en', 'admin.toast.denied.orders', 'You lack permission to view order management. Contact an admin to request access.'),
  ('en', 'admin.toast.denied.matchOps', 'Match operations require the match:update permission.'),
  ('en', 'admin.toast.denied.translations', 'Translations console requires the translation:view permission.'),
  ('en', 'admin.toast.denied.membership', 'Membership console requires the membership:member:view permission.'),
  ('en', 'admin.toast.denied.fundraising', 'Fundraising console requires the fundraising:donation:view permission.'),
  ('en', 'admin.toast.denied.reports', 'Reports require the reports:view permission.'),
  ('en', 'admin.shell.menu.aria', 'Toggle navigation'),
  ('en', 'admin.shell.menu.label', 'Menu'),
  ('en', 'admin.shell.menu.sheetTitle', 'Navigation'),
  ('en', 'admin.shell.search.placeholder', 'Search ops…'),
  ('en', 'admin.shell.language.toggleLabel', 'Lang'),
  ('en', 'admin.shell.quickActions', 'Quick actions'),
  ('en', 'admin.shell.signOut', 'Sign out'),
  ('en', 'admin.toast.shop.orders.loadFailed', 'Failed to load shop orders'),
  ('en', 'admin.toast.shop.orders.updated', 'Order updated'),
  ('en', 'admin.toast.shop.orders.updateFailed', 'Failed to update order'),
  ('en', 'admin.toast.shop.orders.noteAdded', 'Note added'),
  ('en', 'admin.toast.shop.orders.noteFailed', 'Failed to add note'),
  ('en', 'admin.toast.shop.orders.trackingUpdated', 'Tracking updated'),
  ('en', 'admin.toast.shop.orders.trackingFailed', 'Failed to update tracking'),
  ('en', 'admin.shop.orders.table.order', 'Order'),
  ('en', 'admin.shop.orders.table.when', 'When'),
  ('en', 'admin.shop.orders.table.customer', 'Customer'),
  ('en', 'admin.shop.orders.table.items', 'Items'),
  ('en', 'admin.shop.orders.table.total', 'Total'),
  ('en', 'admin.shop.orders.table.status', 'Status'),
  ('en', 'admin.shop.orders.table.tracking', 'Tracking'),
  ('en', 'admin.shop.orders.actions.addNote', 'Add Note'),
  ('en', 'admin.shop.orders.actions.saveTracking', 'Save'),
  ('en', 'admin.form.shop.orders.note.placeholder', 'Note'),
  ('en', 'admin.form.shop.orders.tracking.placeholder', 'Tracking #'),
  ('en', 'admin.shop.orders.filters.status.label', 'Status'),
  ('en', 'admin.shop.orders.filters.status.placeholder', 'Status'),
  ('en', 'admin.shop.orders.search.placeholder', 'Search order id/email'),
  ('en', 'admin.shop.orders.status.all', 'All'),
  ('en', 'admin.shop.orders.status.pending', 'Pending'),
  ('en', 'admin.shop.orders.status.ready', 'Ready'),
  ('en', 'admin.shop.orders.status.fulfilled', 'Fulfilled'),
  ('en', 'admin.shop.orders.status.cancelled', 'Cancelled'),
  ('en', 'admin.shop.actions.errors.orderIdRequired', 'Order ID required'),
  ('en', 'admin.toast.shop.orders.statusChanged', 'Status changed successfully.'),
  ('en', 'admin.shop.actions.errors.updateFailed', 'Failed to update order'),
  ('en', 'admin.shop.actions.errors.noteRequired', 'Note required'),
  ('en', 'admin.toast.shop.orders.noteRecorded', 'Fulfillment note recorded.'),
  ('en', 'admin.shop.actions.errors.noteFailed', 'Failed to add note'),
  ('en', 'admin.toast.shop.orders.trackingSet', 'Tracking number set.'),
  ('en', 'admin.shop.actions.errors.trackingFailed', 'Failed to update tracking'),
  ('en', 'admin.shop.actions.errors.batchIdsRequired', 'Provide at least one order ID'),
  ('en', 'admin.toast.shop.orders.batchUpdated', 'Batch updated'),
  ('en', 'admin.toast.shop.orders.batchUpdatedCount', '{{count}} orders updated.'),
  ('en', 'admin.shop.actions.errors.batchFailed', 'Failed batch update'),
  ('en', 'admin.toast.shop.orders.batchFailed', 'Batch failed'),
  ('en', 'admin.shop.actions.sections.updateStatus', 'Update Order Status'),
  ('en', 'admin.shop.actions.fields.orderId', 'Order ID'),
  ('en', 'admin.shop.actions.fields.status', 'Status'),
  ('en', 'admin.shop.actions.fields.note', 'Note (optional)'),
  ('en', 'admin.shop.actions.buttons.updateStatus', 'Update Status'),
  ('en', 'admin.shop.actions.buttons.addNote', 'Add Note'),
  ('en', 'admin.shop.actions.sections.updateTracking', 'Update Tracking'),
  ('en', 'admin.shop.actions.fields.trackingNumber', 'Tracking number'),
  ('en', 'admin.shop.actions.buttons.saveTracking', 'Save Tracking'),
  ('en', 'admin.shop.actions.sections.batchUpdate', 'Batch Update Status'),
  ('en', 'admin.shop.actions.fields.batchIds', 'Order IDs (comma separated)'),
  ('en', 'admin.form.shop.orders.batchIds.placeholder', 'id1, id2, id3'),
  ('en', 'admin.form.shop.orders.batchStatus.placeholder', 'fulfilled'),
  ('en', 'admin.shop.actions.buttons.runBatch', 'Run Batch Update'),
  ('en', 'admin.form.shop.orders.status.placeholder', 'pending | ready | fulfilled | cancelled'),
  ('en', 'admin.toast.reports.scheduleCreated', 'Schedule created'),
  ('en', 'admin.toast.reports.scheduleSaved', 'Report schedule saved successfully.'),
  ('en', 'admin.toast.reports.scheduleFailed', 'Failed to create schedule'),
  ('en', 'admin.reports.inline.title', 'Report automation'),
  ('en', 'admin.reports.inline.description', 'Generate CSV exports and deliver them to an email or webhook destination on a schedule.'),
  ('en', 'admin.form.reports.schedule.name.placeholder', 'Report name'),
  ('en', 'admin.form.reports.schedule.cron.placeholder', 'Cron expression'),
  ('en', 'admin.form.reports.schedule.destination.placeholder', 'Destination'),
  ('en', 'admin.form.reports.schedule.payload.placeholder', 'Payload JSON (e.g. {"range":"last7"})'),
  ('en', 'admin.reports.schedule.saveButton', 'Save schedule'),
  ('en', 'admin.reports.list.title', 'Active schedules'),
  ('en', 'admin.reports.list.description', 'Configured report deliveries.'),
  ('en', 'admin.toast.rewards.queued', 'Reward queued'),
  ('en', 'admin.toast.rewards.issued', 'Retro reward issued successfully.'),
  ('en', 'admin.toast.rewards.failed', 'Failed to issue reward'),
  ('en', 'admin.rewards.inline.title', 'Retro issue rewards'),
  ('en', 'admin.rewards.inline.description', 'Grant loyalty points or ticket perks when reconciling transactions or handling support cases.'),
  ('en', 'admin.form.rewards.userId.placeholder', 'User id'),
  ('en', 'admin.form.rewards.points.placeholder', 'Points (optional)'),
  ('en', 'admin.form.rewards.matchId.placeholder', 'Match id for ticket perk'),
  ('en', 'admin.form.rewards.reason.placeholder', 'Reason or note'),
  ('en', 'admin.rewards.actions.issue', 'Issue reward'),
  ('en', 'admin.rewards.list.title', 'Recent events'),
  ('en', 'admin.rewards.list.description', 'Latest loyalty events recorded in Supabase.'),
  ('en', 'admin.toast.services.policyIssued', 'Policy issued'),
  ('en', 'admin.toast.services.policyIssuedDescription', 'The policy has been issued successfully.'),
  ('en', 'admin.toast.services.policyFailed', 'Failed to issue policy'),
  ('en', 'admin.toast.services.depositStatus', 'Status set to {{status}}.'),
  ('en', 'admin.toast.services.depositUpdated', 'Deposit updated'),
  ('en', 'admin.toast.services.depositFailed', 'Failed to update deposit'),
  ('en', 'admin.services.insurance.inlineTitle', 'Insurance'),
  ('en', 'admin.services.insurance.inlineDescription', 'Review paid quotes, issue policies, and grant perks where applicable.'),
  ('en', 'admin.services.insurance.listTitle', 'Quotes'),
  ('en', 'admin.services.insurance.listDescription', 'Quotes awaiting issuance or follow-up.'),
  ('en', 'admin.services.insurance.actions.edit', 'Edit'),
  ('en', 'admin.services.insurance.actions.issue', 'Issue policy'),
  ('en', 'admin.services.deposits.inlineTitle', 'SACCO Deposits'),
  ('en', 'admin.services.deposits.inlineDescription', 'Confirm SACCO deposits once reconciled via SMS or ledger uploads.'),
  ('en', 'admin.services.deposits.listTitle', 'Deposits'),
  ('en', 'admin.services.deposits.listDescription', 'Recent SACCO deposits awaiting confirmation.'),
  ('en', 'admin.services.deposits.actions.markPending', 'Mark pending'),
  ('en', 'admin.services.deposits.actions.markConfirmed', 'Mark confirmed'),
  ('en', 'admin.services.insurance.drawerTitle', 'Update quote'),
  ('en', 'admin.services.insurance.drawerDescription', 'Adjust quote metadata or ticket perk eligibility.'),
  ('en', 'admin.toast.services.quoteUpdated', 'Quote updated'),
  ('en', 'admin.toast.services.quoteSaved', 'Changes applied successfully.'),
  ('en', 'admin.toast.services.quoteFailed', 'Failed to update quote'),
  ('en', 'admin.services.insurance.fields.status', 'Status'),
  ('en', 'admin.services.insurance.fields.ticketPerk', 'Ticket perk'),
  ('en', 'admin.services.deposits.confirmTitle', 'Confirm deposit'),
  ('en', 'admin.services.deposits.confirmDescription', 'Are you sure this SACCO deposit is reconciled?'),
  ('en', 'admin.services.deposits.confirmAction', 'Confirm deposit'),
  ('en', 'admin.shared.cancel', 'Cancel'),
  ('en', 'admin.toast.content.saved', 'Content saved'),
  ('en', 'admin.toast.content.draftCreated', 'Draft created successfully.'),
  ('en', 'admin.toast.content.saveFailed', 'Failed to save content'),
  ('en', 'admin.content.inline.title', 'Content library'),
  ('en', 'admin.content.inline.description', 'Manage articles and media scheduled for the fan-facing experience.'),
  ('en', 'admin.content.create.heading', 'Create draft'),
  ('en', 'admin.form.content.title.placeholder', 'Title'),
  ('en', 'admin.form.content.slug.placeholder', 'Slug (optional)'),
  ('en', 'admin.form.content.body.placeholder', 'Body markdown'),
  ('en', 'admin.content.create.saveButton', 'Save draft'),
  ('en', 'admin.content.list.title', 'Recent drafts'),
  ('en', 'admin.content.list.description', 'Draft and published content sorted by last update.')
on conflict (lang, key) do update set value = excluded.value;

insert into public.translations (lang, key, value) values
  ('rw', 'admin.shell.nav.disabled', 'Yahagaritswe'),
  ('rw', 'admin.toast.denied.title', 'Uburenganzira bwanzwe'),
  ('rw', 'admin.toast.denied.generic', 'Nta burenganzira ufite bwo kwinjira muri icyo gice.'),
  ('rw', 'admin.toast.denied.orders', 'Nta burenganzira ufite bwo kureba gucunga amabwiriza. Vugana n''umuyobozi usabe kwemererwa.'),
  ('rw', 'admin.toast.denied.matchOps', 'Imirimo yo ku mukino isaba uburenganzira match:update.'),
  ('rw', 'admin.toast.denied.translations', 'Ihuriro ryo guhindura amavuga risaba uburenganzira translation:view.'),
  ('rw', 'admin.toast.denied.membership', 'Ihuriro rya membership risaba uburenganzira membership:member:view.'),
  ('rw', 'admin.toast.denied.fundraising', 'Ihuriro rya fundraising risaba uburenganzira fundraising:donation:view.'),
  ('rw', 'admin.toast.denied.reports', 'Amakuru bisaba uburenganzira reports:view.'),
  ('rw', 'admin.shell.menu.aria', 'Hindura navigation'),
  ('rw', 'admin.shell.menu.label', 'Menu'),
  ('rw', 'admin.shell.menu.sheetTitle', 'Navigation'),
  ('rw', 'admin.shell.search.placeholder', 'Shakisha imirimo…'),
  ('rw', 'admin.shell.language.toggleLabel', 'Ururimi'),
  ('rw', 'admin.shell.quickActions', 'Ibikorwa byihuse'),
  ('rw', 'admin.shell.signOut', 'Sohoka'),
  ('rw', 'admin.toast.shop.orders.loadFailed', 'Ntibyashobotse gukurura amabwiriza ya shop'),
  ('rw', 'admin.toast.shop.orders.updated', 'Itegeko rihinduwe'),
  ('rw', 'admin.toast.shop.orders.updateFailed', 'Ntibyashobotse kuvugurura itegeko'),
  ('rw', 'admin.toast.shop.orders.noteAdded', 'Inyandiko yongewe'),
  ('rw', 'admin.toast.shop.orders.noteFailed', 'Ntibyashobotse kongeramo inyandiko'),
  ('rw', 'admin.toast.shop.orders.trackingUpdated', 'Umurongo w''ikurikirana wahinduwe'),
  ('rw', 'admin.toast.shop.orders.trackingFailed', 'Ntibyashobotse kuvugurura imyirondoro y''ikurikirana'),
  ('rw', 'admin.shop.orders.table.order', 'Itegeko'),
  ('rw', 'admin.shop.orders.table.when', 'Igihe'),
  ('rw', 'admin.shop.orders.table.customer', 'Umuguzi'),
  ('rw', 'admin.shop.orders.table.items', 'Ibicuruzwa'),
  ('rw', 'admin.shop.orders.table.total', 'Igiteranyo'),
  ('rw', 'admin.shop.orders.table.status', 'Imiterere'),
  ('rw', 'admin.shop.orders.table.tracking', 'Ikurikirana'),
  ('rw', 'admin.shop.orders.actions.addNote', 'Ongeraho inyandiko'),
  ('rw', 'admin.shop.orders.actions.saveTracking', 'Bika'),
  ('rw', 'admin.form.shop.orders.note.placeholder', 'Inyandiko'),
  ('rw', 'admin.form.shop.orders.tracking.placeholder', 'Numero y''ikurikirana'),
  ('rw', 'admin.shop.orders.filters.status.label', 'Imiterere'),
  ('rw', 'admin.shop.orders.filters.status.placeholder', 'Imiterere'),
  ('rw', 'admin.shop.orders.search.placeholder', 'Shakisha ID cyangwa email y''itegeko'),
  ('rw', 'admin.shop.orders.status.all', 'Byose'),
  ('rw', 'admin.shop.orders.status.pending', 'Bitegereje'),
  ('rw', 'admin.shop.orders.status.ready', 'Byiteguye'),
  ('rw', 'admin.shop.orders.status.fulfilled', 'Byuzuye'),
  ('rw', 'admin.shop.orders.status.cancelled', 'Byahagaritswe'),
  ('rw', 'admin.shop.actions.errors.orderIdRequired', 'ID y''itegeko irakenewe'),
  ('rw', 'admin.toast.shop.orders.statusChanged', 'Imiterere yahinduwe neza.'),
  ('rw', 'admin.shop.actions.errors.updateFailed', 'Ntibyashobotse kuvugurura itegeko'),
  ('rw', 'admin.shop.actions.errors.noteRequired', 'Inyandiko irakenewe'),
  ('rw', 'admin.toast.shop.orders.noteRecorded', 'Inyandiko yo kurangiza yanditswe.'),
  ('rw', 'admin.shop.actions.errors.noteFailed', 'Ntibyashobotse kongeramo inyandiko'),
  ('rw', 'admin.toast.shop.orders.trackingSet', 'Numero y''ikurikirana yashyizweho.'),
  ('rw', 'admin.shop.actions.errors.trackingFailed', 'Ntibyashobotse kuvugurura imyirondoro y''ikurikirana'),
  ('rw', 'admin.shop.actions.errors.batchIdsRequired', 'Tanga nibura ID imwe y''itegeko'),
  ('rw', 'admin.toast.shop.orders.batchUpdated', 'Ibyemezo by''itsinda byavuguruwe'),
  ('rw', 'admin.toast.shop.orders.batchUpdatedCount', '{{count}} byavuguruwe.'),
  ('rw', 'admin.shop.actions.errors.batchFailed', 'Ntibyashobotse kuvugurura itsinda'),
  ('rw', 'admin.toast.shop.orders.batchFailed', 'Itsinda ryananiwe'),
  ('rw', 'admin.shop.actions.sections.updateStatus', 'Hindura imiterere y''itegeko'),
  ('rw', 'admin.shop.actions.fields.orderId', 'ID y''itegeko'),
  ('rw', 'admin.shop.actions.fields.status', 'Imiterere'),
  ('rw', 'admin.shop.actions.fields.note', 'Inyandiko (si ngombwa)'),
  ('rw', 'admin.shop.actions.buttons.updateStatus', 'Hindura imiterere'),
  ('rw', 'admin.shop.actions.buttons.addNote', 'Ongeraho inyandiko'),
  ('rw', 'admin.shop.actions.sections.updateTracking', 'Hindura ikurikirana'),
  ('rw', 'admin.shop.actions.fields.trackingNumber', 'Numero y''ikurikirana'),
  ('rw', 'admin.shop.actions.buttons.saveTracking', 'Bika ikurikirana'),
  ('rw', 'admin.shop.actions.sections.batchUpdate', 'Hindura itsinda rimwe'),
  ('rw', 'admin.shop.actions.fields.batchIds', 'IDs z''amategeko (zatandukanyijwe na koma)'),
  ('rw', 'admin.form.shop.orders.batchIds.placeholder', 'id1, id2, id3'),
  ('rw', 'admin.form.shop.orders.batchStatus.placeholder', 'byuzuye'),
  ('rw', 'admin.shop.actions.buttons.runBatch', 'Tangira kuvugurura itsinda'),
  ('rw', 'admin.form.shop.orders.status.placeholder', 'pending | ready | fulfilled | cancelled'),
  ('rw', 'admin.toast.reports.scheduleCreated', 'Igenamigambi ryakozwe'),
  ('rw', 'admin.toast.reports.scheduleSaved', 'Igenamigambi ry''amakuru ryabitswe neza.'),
  ('rw', 'admin.toast.reports.scheduleFailed', 'Ntibyashobotse gukora igenamigambi'),
  ('rw', 'admin.reports.inline.title', 'Gahunda y''amakuru'),
  ('rw', 'admin.reports.inline.description', 'Kora inyandiko za CSV uzohereze kuri email cyangwa webhook kuri gahunda.'),
  ('rw', 'admin.form.reports.schedule.name.placeholder', 'Izina ry''raporo'),
  ('rw', 'admin.form.reports.schedule.cron.placeholder', 'Imiterere ya cron'),
  ('rw', 'admin.form.reports.schedule.destination.placeholder', 'Ahogerekezwa'),
  ('rw', 'admin.form.reports.schedule.payload.placeholder', 'Payload JSON (urugero {"range":"last7"})'),
  ('rw', 'admin.reports.schedule.saveButton', 'Bika gahunda'),
  ('rw', 'admin.reports.list.title', 'Gahunda zikora'),
  ('rw', 'admin.reports.list.description', 'Igenamigambi ry''inyandiko ryateguwe.'),
  ('rw', 'admin.toast.rewards.queued', 'Igihembo cyashyizwe ku murongo'),
  ('rw', 'admin.toast.rewards.issued', 'Igihembo cyahise gitangwa neza.'),
  ('rw', 'admin.toast.rewards.failed', 'Ntibyashobotse gutanga igihembo'),
  ('rw', 'admin.rewards.inline.title', 'Tanga ibihembo by''inyongera'),
  ('rw', 'admin.rewards.inline.description', 'Tanga amanota cyangwa amatike iyo urangije kubara cyangwa gukemura ibibazo.'),
  ('rw', 'admin.form.rewards.userId.placeholder', 'ID y''umukiriya'),
  ('rw', 'admin.form.rewards.points.placeholder', 'Amanota (si ngombwa)'),
  ('rw', 'admin.form.rewards.matchId.placeholder', 'ID y''umukino w''itike'),
  ('rw', 'admin.form.rewards.reason.placeholder', 'Impamvu cyangwa inyandiko'),
  ('rw', 'admin.rewards.actions.issue', 'Tanga igihembo'),
  ('rw', 'admin.rewards.list.title', 'Ibyabaye vuba'),
  ('rw', 'admin.rewards.list.description', 'Ibikorwa bya lojalite biheruka muri Supabase.'),
  ('rw', 'admin.toast.services.policyIssued', 'Polisi yatanzwe'),
  ('rw', 'admin.toast.services.policyIssuedDescription', 'Polisi yatanzwe neza.'),
  ('rw', 'admin.toast.services.policyFailed', 'Ntibyashobotse gutanga polisi'),
  ('rw', 'admin.toast.services.depositStatus', 'Imiterere yashyizwe kuri {{status}}.'),
  ('rw', 'admin.toast.services.depositUpdated', 'Kubitsa byavuguruwe'),
  ('rw', 'admin.toast.services.depositFailed', 'Ntibyashobotse kuvugurura kubitsa'),
  ('rw', 'admin.services.insurance.inlineTitle', 'Ubwishingizi'),
  ('rw', 'admin.services.insurance.inlineDescription', 'Suzuma devisi zishyuwe, utange polisi, kandi usezerereho ibyombi bikenewe.'),
  ('rw', 'admin.services.insurance.listTitle', 'Devisi'),
  ('rw', 'admin.services.insurance.listDescription', 'Devisi zitegereje gutangwa cyangwa gukurikiranwa.'),
  ('rw', 'admin.services.insurance.actions.edit', 'Hindura'),
  ('rw', 'admin.services.insurance.actions.issue', 'Tanga polisi'),
  ('rw', 'admin.services.deposits.inlineTitle', 'Kwishyura kwa SACCO'),
  ('rw', 'admin.services.deposits.inlineDescription', 'Emeza kubitsa kwa SACCO umaze kubihuza na SMS cyangwa amakaye.'),
  ('rw', 'admin.services.deposits.listTitle', 'Kubitsa'),
  ('rw', 'admin.services.deposits.listDescription', 'Kubitsa kwa SACCO gutegereje kwemezwa.'),
  ('rw', 'admin.services.deposits.actions.markPending', 'Shyira mu bitegereje'),
  ('rw', 'admin.services.deposits.actions.markConfirmed', 'Shyira mu byemejwe'),
  ('rw', 'admin.services.insurance.drawerTitle', 'Hindura devisi'),
  ('rw', 'admin.services.insurance.drawerDescription', 'Hindura amakuru ya devisi cyangwa uko itanga itike.'),
  ('rw', 'admin.toast.services.quoteUpdated', 'Devisi yavuguruwe'),
  ('rw', 'admin.toast.services.quoteSaved', 'Impinduka zasohotse neza.'),
  ('rw', 'admin.toast.services.quoteFailed', 'Ntibyashobotse kuvugurura devisi'),
  ('rw', 'admin.services.insurance.fields.status', 'Imiterere'),
  ('rw', 'admin.services.insurance.fields.ticketPerk', 'Itike y''inyongera'),
  ('rw', 'admin.services.deposits.confirmTitle', 'Emeza kubitsa'),
  ('rw', 'admin.services.deposits.confirmDescription', 'Ese koko aya mafaranga ya SACCO yemejwe?'),
  ('rw', 'admin.services.deposits.confirmAction', 'Emeza kubitsa'),
  ('rw', 'admin.shared.cancel', 'Hagarika'),
  ('rw', 'admin.toast.content.saved', 'Ibigitekerezo byabitswe'),
  ('rw', 'admin.toast.content.draftCreated', 'Icyegeranyo cy''inyandiko cyakozwe neza.'),
  ('rw', 'admin.toast.content.saveFailed', 'Ntibyashobotse kubika ibikubiyemo'),
  ('rw', 'admin.content.inline.title', 'Isomero ry''ibikubiyemo'),
  ('rw', 'admin.content.inline.description', 'Tunganya inyandiko n''ibinyamakuru byateganyirijwe abafana.'),
  ('rw', 'admin.content.create.heading', 'Kora umushinga'),
  ('rw', 'admin.form.content.title.placeholder', 'Umutwe'),
  ('rw', 'admin.form.content.slug.placeholder', 'Slug (si ngombwa)'),
  ('rw', 'admin.form.content.body.placeholder', 'Umubiri wa markdown'),
  ('rw', 'admin.content.create.saveButton', 'Bika umushinga'),
  ('rw', 'admin.content.list.title', 'Imishinga iheruka'),
  ('rw', 'admin.content.list.description', 'Ibikubiyemo by''imishinga n''ibyasohotse bigenekereje igihe byavuguruwe.')
on conflict (lang, key) do update set value = excluded.value;
