import type { z } from 'zod';

type RuntimeEnv = {
  APP_ENV: 'local' | 'development' | 'staging' | 'production' | 'test';
  NODE_ENV: 'development' | 'test' | 'production';
  APP_BASE_URL?: string;
  NEXT_PUBLIC_SITE_URL?: string;
  NEXT_PUBLIC_BACKEND_URL: string;
  NEXT_PUBLIC_ENVIRONMENT_LABEL: string;
  NEXT_PUBLIC_SUPABASE_URL: string;
  NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY?: string;
  NEXT_PUBLIC_ONBOARDING_PUBLIC_TOKEN: string;
  NEXT_PUBLIC_FEATURE_FLAGS: string;
  NEXT_PUBLIC_SOCKET_TRANSPORT?: string;
  NEXT_PUBLIC_SOCKET_PATH?: string;
  NEXT_PUBLIC_TELEMETRY_URL?: string;
  NEXT_PUBLIC_SENTRY_DSN?: string;
  NEXT_PUBLIC_OPENAI_BASE_URL?: string;
  NEXT_PUBLIC_ADMIN_SESSION_COOKIE?: string;
  NEXT_PUBLIC_ADMIN_API_TOKEN?: string;
  NEXT_PUBLIC_ONBOARDING_ALLOW_MOCK?: string;
  PORT?: string;
  SUPABASE_SERVICE_ROLE_KEY: string;
  SITE_SUPABASE_URL: string;
  SITE_SUPABASE_SECRET_KEY: string;
  SUPABASE_SERVICE_KEY?: string;
  SUPABASE_URL?: string;
  SUPABASE_SECRET_KEY?: string;
  SITE_SUPABASE_PUBLISHABLE_KEY?: string;
  SUPABASE_PUBLISHABLE_KEY?: string;
  SUPABASE_ANON_KEY?: string;
  ONBOARDING_API_TOKEN: string;
  ONBOARDING_ALLOW_MOCK?: string;
  OPENAI_API_KEY: string;
  AGENT_ID?: string;
  NEXT_PHASE?: string;
  NEXT_RUNTIME?: string;
  CI?: string;
  E2E_API_MOCKS?: string;
  SENTRY_DSN?: string;
  SENTRY_TRACES_SAMPLE_RATE?: string;
  SENTRY_REPLAYS_SESSION_SAMPLE_RATE?: string;
  SENTRY_REPLAYS_ERROR_SAMPLE_RATE?: string;
};

type ServerEnv = {
  APP_ENV: RuntimeEnv['APP_ENV'];
  NODE_ENV: RuntimeEnv['NODE_ENV'];
  APP_BASE_URL: string;
  NEXT_PUBLIC_SITE_URL?: string;
  NEXT_PUBLIC_BACKEND_URL: string;
  NEXT_PUBLIC_ENVIRONMENT_LABEL: string;
  NEXT_PUBLIC_SUPABASE_URL: string;
  NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY?: string;
  NEXT_PUBLIC_ONBOARDING_PUBLIC_TOKEN: string;
  NEXT_PUBLIC_FEATURE_FLAGS: string;
  NEXT_PUBLIC_SOCKET_TRANSPORT?: string;
  NEXT_PUBLIC_SOCKET_PATH?: string;
  NEXT_PUBLIC_TELEMETRY_URL?: string;
  NEXT_PUBLIC_SENTRY_DSN?: string;
  NEXT_PUBLIC_OPENAI_BASE_URL?: string;
  NEXT_PUBLIC_ADMIN_SESSION_COOKIE?: string;
  NEXT_PUBLIC_ADMIN_API_TOKEN?: string;
  NEXT_PUBLIC_ONBOARDING_ALLOW_MOCK?: string;
  PORT?: string;
  SUPABASE_SERVICE_ROLE_KEY: string;
  SITE_SUPABASE_URL: string;
  SITE_SUPABASE_SECRET_KEY: string;
  SUPABASE_SERVICE_KEY?: string;
  SUPABASE_URL?: string;
  SUPABASE_SECRET_KEY?: string;
  SITE_SUPABASE_PUBLISHABLE_KEY?: string;
  SUPABASE_PUBLISHABLE_KEY?: string;
  SUPABASE_ANON_KEY?: string;
  ONBOARDING_API_TOKEN: string;
  ONBOARDING_ALLOW_MOCK?: string;
  OPENAI_API_KEY: string;
  AGENT_ID?: string;
  NEXT_PHASE?: string;
  NEXT_RUNTIME?: string;
  CI?: string;
  E2E_API_MOCKS?: string;
  SENTRY_DSN?: string;
  SENTRY_TRACES_SAMPLE_RATE?: string;
  SENTRY_REPLAYS_SESSION_SAMPLE_RATE?: string;
  SENTRY_REPLAYS_ERROR_SAMPLE_RATE?: string;
};

type ClientEnv = {
  NEXT_PUBLIC_SITE_URL: string;
  NEXT_PUBLIC_BACKEND_URL: string;
  NEXT_PUBLIC_ENVIRONMENT_LABEL: string;
  NEXT_PUBLIC_SUPABASE_URL: string;
  NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY?: string;
  NEXT_PUBLIC_ONBOARDING_PUBLIC_TOKEN: string;
  NEXT_PUBLIC_FEATURE_FLAGS: string;
  NEXT_PUBLIC_SOCKET_TRANSPORT?: string;
  NEXT_PUBLIC_SOCKET_PATH?: string;
  NEXT_PUBLIC_TELEMETRY_URL?: string;
  NEXT_PUBLIC_SENTRY_DSN?: string;
  NEXT_PUBLIC_OPENAI_BASE_URL?: string;
  NEXT_PUBLIC_ADMIN_SESSION_COOKIE?: string;
  NEXT_PUBLIC_ADMIN_API_TOKEN?: string;
  NEXT_PUBLIC_ONBOARDING_ALLOW_MOCK?: string;
};

type RuntimeConfig = {
  appEnv: RuntimeEnv['APP_ENV'];
  port: string;
  server: ServerEnv;
  client: ClientEnv;
};

export declare const envSchema: z.ZodType<RuntimeEnv>;
export declare const serverEnv: ServerEnv;
export declare const clientEnv: ClientEnv;
export declare const runtimeConfig: RuntimeConfig;

export type { ClientEnv, RuntimeConfig, RuntimeEnv, ServerEnv };
