// This file is automatically generated. Do not edit it directly.
import type { SupabaseClient } from "@supabase/supabase-js";

import { createBrowserClient, SupabaseConfigurationError } from "@rayon/api/supabase";
import type { Database } from "@rayon/api/types/database";

let singleton: SupabaseClient<Database> | null = null;

export const getSupabaseClient = (): SupabaseClient<Database> | null => {
  if (singleton) {
    return singleton;
  }

  try {
    singleton = createBrowserClient();
    return singleton;
  } catch (error) {
    if (error instanceof SupabaseConfigurationError) {
      if (process.env.NODE_ENV !== "production") {
        console.warn(
          "[supabase] Missing Supabase browser credentials. Rewards widget will be disabled until configured.",
        );
      }
      return null;
    }
    throw error;
  }
};

export const supabase = getSupabaseClient();
