name: Supabase Functions Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/functions/**'
      - '.github/workflows/supabase-functions-deploy.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: supabase-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Supabase CLI
        run: npm i -g supabase

      - name: Show Supabase CLI version
        run: supabase --version

      - name: Link project
        run: supabase link --project-ref "$SUPABASE_PROJECT_REF"
        # Authenticated via SUPABASE_ACCESS_TOKEN env above (no prompt)

      - name: Deploy all functions
        run: supabase functions deploy --project-ref "$SUPABASE_PROJECT_REF"
        # If you want to deploy only changed functions, script a diff here.

      # Optional: set/refresh function secrets from repo secrets
      # - name: Sync function secrets (example)
      #   run: |
      #     supabase secrets set OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} --project-ref "$SUPABASE_PROJECT_REF"
